name: Create PDF File

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          npm ci

      - name: Generate PDF
        run: |
          bash generate.sh

      - uses: actions/upload-artifact@v4
        with:
          name: rahul_resume
          path: output/rahul_resume.pdf
