name: Create PDF File

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: "Create a folder called output"
        run: |
          mkdir output

      - name: "Install pandoc"
        run: |
          wget https://github.com/jgm/pandoc/releases/download/3.0.1/pandoc-3.0.1-1-amd64.deb
          sudo apt install pandoc
          sudo apt install nodejs
          sudo apt install npm
          npm install

      - name: "Run the script"
        run: |
          bash generate.sh

      - uses: actions/upload-artifact@master
        with:
          name: ${{ github.actor }}'s Resume
          path: output
